//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCCIOct30_2017CarDealershipDBPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Buyer
    {
        public int Car_BuyerID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public int CarID { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Car Car { get; set; }
    }
}
